let nombre="Marcia";
let apellido="Gomez";
let numerouno=12;
let numerodos=8;
let numerotres=4;
let suma = numerouno + numerodos;
let suma2 = suma + numerotres;
console.log ("Nombre y Apellido:",nombre,"",apellido);
console.log ("Suma de las primeras dos variables:",suma);
console.log ("Suma de las primeras dos variables mas la tercer variable:",suma2);
